### ISSUE TITLE
Time in force undefined is unknown

### ISSUE THREAD

**Issue by yannickjemmely** [Reiryoku-Technologies/Mida#110] opened 2023-05-12 23:17 UTC
Running the trading system or market component example bring this issue on Bybit
![image](https://github.com/Reiryoku-Technologies/Mida/assets/877452/843f2866-28a2-43ca-b6e2-db8dbd8d4ac3)

**Comment by Vasile-Peste** [comment] 2023-05-13 09:53
Thank you for the PR! Going to release this soon

**Comment by Vasile-Peste** [comment] 2023-05-14 09:08
Hey! [2023.3](https://github.com/Reiryoku-Technologies/Mida/releases/tag/v2023.3.0) is out, please can you check that the issue is fixed so we can close the issue?

Thank you!

**Comment by Vasile-Peste** [comment] 2023-05-15 13:10
Closing since we already received positive feedback for the fix,
@yannickjemmely thank you again for your contribution!

**Closed by Vasile-Peste** 2023-05-15 13:10 UTC
Labels: bug
